/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Matrix1635 (https://sketchfab.com/Matrix1635)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/low-poly-button-optimized-for-roblox-51456146478740dba6469a4c04435c3c
Title: Low Poly Button - Optimized For Roblox
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { RigidBody } from '@react-three/rapier'

export function Button({ onCollide, onLeave, ...props }) {
    const group = useRef();
    const { nodes, materials, animations } = useGLTF('/models/button.glb');
    const { actions } = useAnimations(animations, group);

    return (
        <RigidBody type="fixed" colliders="cuboid"
            onCollisionEnter={({ other }) => {
                if (other.rigidBodyObject?.userData?.isCharacter) {
                    onCollide?.();
                }
            }}
            onCollisionExit={({ other }) => {
                if (other.rigidBodyObject?.userData?.isCharacter) {
                    onLeave?.();
                }
            }}>
            <group ref={group} {...props} dispose={null}>
                <group name="Sketchfab_Scene">
                    <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
                        <group
                            name="d757a1532ad54fc598cab5f4bcbe806cfbx"
                            rotation={[Math.PI / 2, 0, 0]}
                            scale={0.01}>
                            <group name="Object_2">
                                <group name="RootNode">
                                    <group name="switch" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                                    <group name="switch_armature" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                                        <group name="Object_6">
                                            <primitive object={nodes._rootJoint} />
                                            <skinnedMesh
                                                name="Object_9"
                                                geometry={nodes.Object_9.geometry}
                                                material={materials.UV_switch}
                                                skeleton={nodes.Object_9.skeleton}
                                            />
                                            <group name="Object_8" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                                        </group>
                                    </group>
                                </group>
                            </group>
                        </group>
                    </group>
                </group>
            </group>
        </RigidBody>
    )
}

useGLTF.preload('/models/button.glb')